### ISSUE TITLE
Use a github action for link checking?

### ISSUE THREAD

**Issue by bouweandela** [IS-ENES3/Tests#1]
Nice work @valeriupredoi!

For further improvement, you could consider using an existing GitHub action for link checking. Here is one that I have used in another project: https://github.com/lycheeverse/lychee-action, but I think there's a few more around.

**Comment by valeriupredoi** [comment]
Cheers, man, but nothing compares to writing your own piece of code. Don't take this away from me, I managed to write 100 lines of Python among a bazillion lines of Markdown in the past week, needed that for mental health purposes 😁 I might go about and test the script on our docs, see if it helps, if not I'll close this. The benefit I gathered from my script is that we can tweak the depth we can go to check for broken links

**Comment by valeriupredoi** [comment]
gonna close this if you don't mind @bouweandela 📺
